import ts from 'typescript';
import {spotlightMedia} from './spotlight-media.mjs';
import {panelMedia} from './panel-media.mjs';
import {imageAssets} from './image-assets.mjs';
import {cameraMedia} from './camera-media.mjs';
import {readFileSync,writeFileSync} from 'node:fs';
// Generate instance-local components. Original sources and shared fixture modules stay intact.
export function editableDemo(file, stem) {
 const src=readFileSync(file,'utf8'), ast=ts.createSourceFile(file,src,ts.ScriptTarget.Latest,true,ts.ScriptKind.TSX);
 const edits=[], fields=[], seen=new Map();
 const field=(node,value,type,label)=>{
  const identity=type+':'+value+(type==='number'?':'+node.pos:'');
  let key=seen.get(identity);
  if(!key){key=label==='file'?'file':'content_'+fields.filter(f=>f.key.startsWith('content_')).length;seen.set(identity,key);fields.push({key,type,label:label==='file'?'替换图片':label||`${type==='color'?'颜色':'文字'} ${fields.length+1}`,default:value});}
  let replacement=`(__values[${JSON.stringify(key)}] ?? ${JSON.stringify(value)})`;
  if(ts.isJsxText(node)||ts.isJsxAttribute(node.parent))replacement='{'+replacement+'}';
  edits.push([node.getStart(ast),node.end,replacement]);
 };
 const contentName=/^(text|title|subtitle|headline|label|word|words|name|caption|description|copy|brand|url|src|image|imageUrl|file|value|prefix|suffix|tagline|message|badge|cta|heading|subheading)$/i;
 function visit(n){
  if(ts.isImportDeclaration(n)||ts.isExportDeclaration(n)||ts.isTypeNode(n))return;
  if(ts.isJsxText(n)&&n.text.trim())field(n,n.text.trim(),'text');
  else if(ts.isStringLiteral(n)||ts.isNoSubstitutionTemplateLiteral(n)){
   const p=n.parent;
   const name=(ts.isPropertyAssignment(p)||ts.isVariableDeclaration(p)||ts.isJsxAttribute(p)||ts.isBindingElement(p))?p.name?.getText(ast):'';
   if(/^#[\da-f]{6}$/i.test(n.text))field(n,n.text,'color');
   else if(contentName.test(name||'')||(ts.isJsxExpression(p)&&p.expression===n&&n.text.trim()))field(n,n.text,'text',name==='file'?'file':name?`${name} · ${n.text.slice(0,22)}`:undefined);
   else if(ts.isArrayLiteralExpression(p)&&ts.isVariableDeclaration(p.parent)&&/text|word|title|label|line|phrase|glyph|icon|caption|heading|name/i.test(p.parent.name.getText(ast))&&n.text.trim()&&!/[/\\]|\.(?:png|jpe?g|svg|webp|mp4)$/i.test(n.text))field(n,n.text,'text',`${p.parent.name.getText(ast)} · ${n.text.slice(0,22)}`);
  } else if(ts.isNumericLiteral(n)&&ts.isVariableDeclaration(n.parent)&&n.parent.initializer===n){
   const name=n.parent.name.getText(ast),list=n.parent.parent,stmt=list.parent;
   if(ts.isVariableStatement(stmt)&&stmt.parent===ast&&!/DUR|TOTAL|FRAMES|END|^W$|^H$|WIDTH|HEIGHT|FPS/.test(name))field(n,Number(n.text),'number',name);
  }
  ts.forEachChild(n,visit);
 }
 visit(ast);
 // Keep imports at module scope; all other declarations are instantiated once per props revision.
 const slots=[cameraMedia(ast,stem,edits,fields),spotlightMedia(ast,stem,edits,fields),imageAssets(ast,stem,edits,fields),panelMedia(ast,stem,edits,fields)];
 const imports=ast.statements.filter(ts.isImportDeclaration).map(n=>{
  if(!n.moduleSpecifier.text.endsWith('/Fixtures')) return n.getText(ast);
  let text=n.getText(ast);
  for(const el of n.importClause?.namedBindings?.elements||[]){
   const original=el.propertyName?.text||el.name.text;
   if(!['FakeDashboard','Card'].includes(original))continue;
   const local=el.name.text,key=original==='Card'?'file2':'file';
   text=text.replace(el.getText(ast),`${original} as __Original${local}`);
   slots.push(`const ${local} = (p) => (__values[p.studioSlot] || __values.${key}) ? editableElement('div',{style:{width:p.w??1920,height:p.h??1080,overflow:'hidden',...p.style}},editableElement(EditableImg,{src:editableStaticFile(String(__values[p.studioSlot] || __values.${key})),style:{width:'100%',height:'100%',objectFit:'cover'}})) : editableElement(__Original${local},p);`);
   if(!fields.some(f=>f.key===key))fields.unshift({key,type:'text',label:original==='Card'?'替换卡片图片':'替换网页截图',default:''});
  }
  return text;
 }).join('\n');
 for(const n of ast.statements){
  if(ts.isImportDeclaration(n))edits.push([n.getStart(ast),n.end,'']);
  else for(const m of n.modifiers||[])if(m.kind===ts.SyntaxKind.ExportKeyword||m.kind===ts.SyntaxKind.DefaultKeyword)edits.push([m.getStart(ast),m.end,'']);
 }
 let body=src;for(const [a,b,t] of edits.sort((a,b)=>b[0]-a[0]))body=body.slice(0,a)+t+body.slice(b);
 const generated=`// @ts-nocheck\n// Generated by editable-demos.mjs; do not edit.\n${imports}\nimport {useMemo as useEditableMemo, createElement as editableElement} from 'react';\nimport {Img as EditableImg, staticFile as editableStaticFile} from 'remotion';\nfunction createEditable(__values) {\n${slots.join('\n')}\n${body}\nreturn ${stem};\n}\nexport const ${stem} = (props) => {const signature=JSON.stringify(props);const Component=useEditableMemo(()=>createEditable(props),[signature]);return editableElement(Component);};\n`;
 writeFileSync(file.replace(/\.tsx$/,'.editable.tsx'),generated);
 return fields;
}
