import React,{useState} from 'react';
import {api,notify} from '../desktop-api';
import {useStore,findClip} from '../store';
import {VoiceSettings} from './VoiceSettings';
import {WebsiteCapture} from './WebsiteCapture';
import {uid} from '../types';
export const ProductionPanel:React.FC<{mode:string;onEdit?:()=>void}>=({mode,onEdit})=>{
 const project=useStore(s=>s.project);const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');
 const [captureOpen,setCaptureOpen]=useState(false);
 const voice=project.voiceDraft||{text:'',speaker:'zh_male_liufei_uranus_bigtts',rate:0};
 const draft=(patch:Record<string,unknown>)=>{const s=useStore.getState();s.setProject({...s.project,voiceDraft:{...voice,...patch}})};
 const [result,setResult]=useState<any>(project.voiceResult||null);
 const [alignment,setAlignment]=useState('');
 const run=async()=>{setBusy(true);setMessage('正在生成配音与词时间…');try{const r=await api('voice',voice);setResult(r);const s=useStore.getState();s.setProject({...s.project,voiceResult:r});setMessage(r.verified?'已取得经过校验的原生词时间':'配音完成，词时间未验证');window.dispatchEvent(new Event('assets-changed'))}catch(e){setMessage(String(e))}finally{setBusy(false)}};
 const addAudio=()=>{if(!result)return;const s=useStore.getState();let track=s.project.tracks.find(t=>t.name==='配音');if(!track){track={id:uid('track'),name:'配音',clips:[]};s.setProject({...s.project,tracks:[...s.project.tracks,track]})}useStore.getState().addClip('audio-clip',track.id,s.playhead,{props:{file:result.file,volume:1},duration:Math.round(result.duration*30),label:'配音 · '+result.text.slice(0,12)});notify('配音已加入配音轨，已选中音频片段');onEdit?.()};
 const bind=(word:any)=>{const s=useStore.getState();const hit=s.selectedClipId&&findClip(s.project,s.selectedClipId);if(!hit){notify('先选中需要绑定的镜头');return}const audio=s.project.tracks.flatMap(t=>t.clips).find(c=>c.cardId==='audio-clip'&&c.props.file===result?.file);if(!audio){notify('先把这段配音添加到时间线');return}const time=(audio.start+(word.start*s.project.fps-audio.inOffset)/audio.speed-hit.clip.start)/s.project.fps;if(time<0||time>hit.clip.duration/s.project.fps){notify('这个词不在选中镜头的时间范围内');return}s.commit();s.updateClipProps(hit.clip.id,{trigger:time});notify(`动作已绑定「${word.text}」：${time.toFixed(2)} 秒`)};
 if(mode==='capture')return <div className="production-panel"><div className="panel-heading">网页素材<span>框选网页任意位置</span></div><p className="panel-help">加载网页后，在截图预览中滚动和拖动框选，也可以输入坐标和尺寸微调。</p><button className="btn primary wide" onClick={()=>setCaptureOpen(true)}>打开网页截取</button><p className="task-message">{message}</p>{captureOpen&&<WebsiteCapture onClose={()=>setCaptureOpen(false)} onSaved={a=>{setMessage('已存入素材库：'+a.name);setCaptureOpen(false)}}/>}</div>;
 return <div className="production-panel"><div className="panel-heading">豆包配音<span>选择音色、生成音频，再加入导演或时间线</span></div><label>口播文案<textarea aria-label="口播文案" rows={7} value={voice.text} onChange={e=>draft({text:e.target.value})} placeholder="写下这段要说的话…"/></label><label>豆包音色 ID<input aria-label="豆包音色 ID" value={voice.speaker} onChange={e=>draft({speaker:e.target.value})}/></label><label>语速 <span>{voice.rate}</span><input type="range" min="-50" max="100" value={voice.rate} onChange={e=>draft({rate:Number(e.target.value)})}/></label><button className="btn primary wide" disabled={busy||!voice.text.trim()} onClick={run}>{busy?'生成中…':'用豆包生成这一段'}</button><p className="panel-help">首次使用请在下方「豆包 API 设置」填写密钥。生成会调用语音服务；完成后由你决定是否加入时间线。</p><VoiceSettings/><p className="task-message" role="status">{message}</p>{result&&<><audio controls src={'/'+result.file}/><div className="voice-status">{result.verified?'● 已验证逐词时间':'○ 未验证时间'} · {result.duration.toFixed(2)} 秒</div>{result.text!==voice.text&&<p className="warning">文案已更改，下面仍是上次生成的配音。</p>}<button className="btn wide" onClick={addAudio}>＋ 添加到时间线配音轨</button><p className="panel-help">添加后会自动打开视频剪辑并选中这段音频。选中镜头后，点击词语，可将动作时间绑定到该词。</p><div className="word-list">{result.words.map((x:any,i:number)=><button key={i} title={`${x.start.toFixed(2)}–${x.end.toFixed(2)} 秒`} onClick={()=>bind(x)}>{x.text}<small>{x.start.toFixed(2)}</small></button>)}</div></>}
 <details><summary>导入自己的词时间</summary><p className="panel-help">JSON 需包含 provider、audioSha256、words 或 scenes。先在素材库导入音频，再填写下方路径。时间需要与同一音频的哈希及范围匹配。</p><input id="alignment-audio" placeholder="素材路径，如 uploads/…wav"/><textarea rows={4} placeholder="粘贴对齐 JSON" value={alignment} onChange={e=>setAlignment(e.target.value)}/><button className="btn" onClick={async()=>{try{const file=(document.getElementById('alignment-audio') as HTMLInputElement).value;const r=await api('alignment',{file,alignment:JSON.parse(alignment)});setResult(r);const s=useStore.getState();s.setProject({...s.project,voiceResult:r});setMessage('导入完成，时间结构与音频哈希已校验')}catch(e){setMessage(String(e))}}}>校验并导入</button></details></div>
};
